spring.application.name=SB_CRUD
server.port=9090

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/prueba3
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hikari Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

# JDBC LOG
logging.level.org.springframework.jdbc.core=DEBUG

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MyBatis
mybatis.type-aliases-package=com.reinaldo.gestor
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


spring.profiles.active=jpa
