spring.application.name=SpringBoot
server.port=9090

# Configuracion de conexion
spring.datasource.url=jdbc:postgresql://localhost:5432/db_inventario
spring.datasource.username=postgres
spring.datasource.password=Rey231071
