spring.application.name=SB_Blog
server.port=9090

#DB
spring.datasource.url=jdbc:mysql://localhost:3306/sb_blog
spring.datasource.username=root
spring.datasource.password=

#JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
