spring.application.name=SB_Inventario
server.port=9090

# DB
spring.datasource.url=jdbc:mysql://localhost:3306/inventario2
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
