spring.application.name=SB_Seguridad
server.port=9090

#DB
spring.datasource.url=jdbc:h2:mem:seguridaddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#LOG
logging.level.org.springframework.security=DEBUG

#HASH
secret.key=ea3c51e0f0aeb7d4702762569d0e11a688629df99bc2e19baa8a03644e8998f6
